# Set to true to add reviewers to pull requests
addReviewers: true
 
# Set to author to set pr creator as assignee
addAssignees: author 
 
# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewers:
  - ff6edga
  - younsoo-kim
  - younsoo.kim
  - simjunbo


# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1
 
# Hoxy gitmoji를 여기에 ??
# A list of keywords to be skipped the process that add reviewers if pull requests include it
# skipKeywords:
#   - wip
