# Set to true to add reviewers to pull requests
addReviewers: true
 
# Set to author to set pr creator as assignee
addAssignees: author 
 
# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 2
 
# Set to true to add reviewers from different groups to pull requests
useReviewGroups: true
 
# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  2wd-server:
    - younsoo.kim
    - YoungChulShin-Russel
    - ff6edga
 
# Hoxy gitmoji를 여기에 ??
# A list of keywords to be skipped the process that add reviewers if pull requests include it
# skipKeywords:
#   - wip
